language: rust
sudo: false
matrix:
  include:
    - rust: nightly
      env:
       - FEATURES='serde-1'
    - rust: nightly
      env:
       - FEATURES='rayon'
    - rust: nightly
      env:
       - TEST_BENCH=1
    - rust: nightly
      env:
       - FEATURES='test_low_transition_point'
    - rust: nightly
      env: TARGET=thumbv6m-none-eabi
      before_script:
        - rustup target add $TARGET
        - set -ex
      script:
        - cargo build -vv --target=$TARGET
        - cargo build -v -p test-nostd --target=$TARGET
branches:
  only:
    - master
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      if [ -z "$SKIP_TEST" ]; then
        cargo test --verbose --features "$FEATURES" &&
        cargo test --release --verbose --features "$FEATURES"
        if [ "$FEATURES" = "serde-1" ]; then
          cargo test --verbose -p test-serde &&
          cargo test --release --verbose -p test-serde
        fi
      fi &&
      if [ -n "$TEST_BENCH" ]; then
        cargo test -v --benches --no-run --features "$FEATURES"
      fi &&
      cargo doc --verbose --features "$FEATURES"
