[package]
name = "test-serde"
version = "0.1.0"
authors = ["bluss"]
publish = false
edition = "2018"

[dependencies]

[dev-dependencies]
fnv = "1.0"
indexmap = { path = "..", features = ["serde-1"], package = "indexmap-amortized" }
serde_test = "1.0.99"
