[package]
name = "test-nostd"
version = "0.1.0"
authors = ["bluss"]
publish = false
edition = "2018"

[dependencies]
indexmap = { path = "..", features = ["serde-1"], package = "indexmap-amortized" }

[dev-dependencies]
